## Overview

Welcome! Thank you for your interest in the type template for Self Paced Reading Tasks on PCIBex.

This website is intended to serve as a guide to help users correctly modify the existing template and run their own experiments with little effort.

References may be found in the reference portion of this website.

To **begin** this guide, please download the full template code located [here](https://github.com/UMWordLab/ibex_2023_eventive_repl_SPRT).

::: callout-warning
This guide is NOT comprehensive nor meant to teach the PCIBex framework.
:::

## Stimuli Formatting

Let's start with a crucial part of the experiment: the file with the stimuli.

Please follow the formatting of the stimuli found in the [Github Repository](https://github.com/UMWordLab/ibex_2023_eventive_repl_SPRT/blob/main/chunk_includes/Experiment.csv)

You are free to add columns as you see fit for your experiment. However, it is recommended that you maintain the core layout seen in the stimuli linked above.

::: callout-important
## Renaming Files

In order for the experiment to work, you must **rename your .csv to Experiment.csv**
:::

## Shuffle Sequencing

Our shuffle sequence can be seen below.

``` javascript
var shuffleSequence = 
seq("consent", "IDentry", "demo", "intro",
    "startpractice",
                                            
    seq("practice"),
                        
    "setcounter",
    "starter",

    seq(rshuffle(startsWith("mklo"), startsWith("gp"), 
                 startsWith("Subjexp"), startsWith("Objexp"))),
      
    "sendresults",
    "completion"
);
```

Now, assuming you have a properly formatted .csv, you can modify the shuffle sequence.

To make the sequence work for your experiment, please modify the labels inside the startsWith() function to correspond to the "cond1" column of your set of stimuli. Additionally, add or remove calls to startsWith() to work with your set of stimuli.

## ID Collection

Great! now our stimuli are set up. Now, let's consider collecting participant ID.

Our manner of ID collection can be seen below

``` javascript
newTrial("IDentry",
   newText("instr", "Please enter your Prolific ID:").print(),

   newHtml("partpage", "<input type='text' id='partID' name='participant ID' min='1' max='120'>").print(),

   newButton("Next").print().wait(
       getVar("partID").set( v=>$("#partID").val() ).testNot.is('')
   )
)
```

You should not change the underlying functionality of this ID collection. However, please adjust the instructions text and max / min participant IDs such that they work for your experiment.

## Consent and Introduction

To change the text found in the consent and introduction sections of the experiment, please modify the files **intro1.html and consent.html** located in the **chunk_includes** directory.

You do not have to modify any of the HTML Tags if you do not wish to; changing the text only is sufficient.

## Adjusting Running Order

For clarity sake, the instructions for this portion will be outlined in comments found in the actual source code.

In the experiment, you will see a function with the following header:

```javascript 
  function modifyRunningOrder(ro) {

    var new_ro = [];
    item_count=0;
    for (var i in ro) {
      var item = ro[i];
      // fill in the relevant experimental condition names on the next line
      // this is similar to what you had to do in the shuffle sequence
      if (item[0].type.startsWith("mklo")|| item[0].type.startsWith("gp")
            || item[0].type.startsWith("Subjexp") || item[0].type.startsWith("Objexp")) {
          item_count++;
          new_ro.push(item);
        // first number after item count is how many items between breaks. second is total-items - 1
          if (item_count%30===0 & item_count<86){
         // value here should be total_items - items_per_block + blocks added (to trigger message that last block is coming up)
              if (item_count===57 + 3){
                  text="End of block. Only 1 block left!";
                  }
              else {
        // first number is the total number of blocks. second number is number of items per block
                  text="End of block. "+(3-(Math.floor(item_count/30)))+" blocks left.";
              }ro[i].push(new DynamicElement("Message", 
                                { html: "<p>30-second break - stretch and look away from the screen briefly if needed.</p>" + text, transfer: 30000 }));
          }
        } else {
        new_ro.push(item);
        }
    }
    return new_ro;
  }
```
Please follow the instructions outlined by the comments (the grey text)



::: callout-tip
And, **you are done**! If you wanted, you could be done writing code and have a fully functioning experiment on the PCIbex farm
:::



## Optional Changes

If you are a more seasoned user of PCIBex, you could also consider making the following changes.

### Removing Comprehension Questions

Comprehensions can be removed in a 2 step process.

First, remove all relevant columns from your Experiment .csv

Secondly, modify the Template call found in **main.js** in the **data_includes** directory by removing the following chunk of code.

``` javascript
row.comprehension_question ? 
            newController("QuestionAlt", { 
                    as: [["f", row.answerchoice0], ["j",row.answerchoice1]],
                    // is expecting a Number, cast is necessary
                    hasCorrect: Number(row.correct_response),
                    q: row.comprehension_question,
                    randomOrder: false,
                    presentHorizontally: true

```

### Changing DashedSentenceAlt

Our template uses a modified version of DashedSentence titled DashedSentenceAlt.

If some of the underlying functionality of this controller does not fit the needs of your experiment (say you wanted to use a different key to show words), consider modifying the source code of the controller.

Additionally, you may consider scrapping our alternate version of DashedSentence and making your own starting from the DashedSentence provided by PCIBex.

